server:
  port: 8083

spring:
  application:
    name: subscriptionsService
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/my_subscriptions
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  flyway:
    url: jdbc:postgresql://localhost:5432/my_subscriptions
    user: postgres
    password: postgres
    schemas: public,subscriptions_service
    sql-migration-prefix: V
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
    com.webriz.subscriptionsservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/subscriptions-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7