spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service-route
          predicates:
            - Path=/users/**
          uri: http://user-service:8082

        - id: subscriptions-service-route
          predicates:
            - Path=/subscriptions/**
          uri: http://subscriptions-service:8083

server:
  port: 8081