CREATE TABLE subscriptions_service.model
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID,
    name VARCHAR(255),
    CONSTRAINT pk_model PRIMARY KEY (id)
);

CREATE TABLE subscriptions_service.model_to_subscriptions
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_id BIGINT,
    sub_id   BIGINT,
    count    BIGINT,
    CONSTRAINT pk_model_to_subscriptions PRIMARY KEY (id)
);

CREATE TABLE subscriptions_service.subscriptions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID,
    model_uuid UUID,
    user_uuid  UUID,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_subscriptions PRIMARY KEY (id)
);

ALTER TABLE subscriptions_service.model
    ADD CONSTRAINT uc_model_uuid UNIQUE (uuid);

ALTER TABLE subscriptions_service.subscriptions
    ADD CONSTRAINT uc_subscriptions_uuid UNIQUE (uuid);

ALTER TABLE subscriptions_service.model_to_subscriptions
    ADD CONSTRAINT FK_MODEL_TO_SUBSCRIPTIONS_ON_MODEL FOREIGN KEY (model_id) REFERENCES subscriptions_service.model (id);

ALTER TABLE subscriptions_service.model_to_subscriptions
    ADD CONSTRAINT FK_MODEL_TO_SUBSCRIPTIONS_ON_SUB FOREIGN KEY (sub_id) REFERENCES subscriptions_service.subscriptions (id);